# Generated by Django 4.1.5 on 2023-03-08 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 8, 11, 49, 51, 195070))),
                ('title', models.CharField(max_length=200)),
                ('cate', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploded_files')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 8, 11, 49, 51, 195070)),
        ),
    ]
